### ISSUE TITLE
profilecard-tips

### ISSUE THREAD

**Issue by yujing-student** [yujing-student/your-tribe-for-life-profile-card#1]
Dit is het idee wat ik nu heb zie de figma file
https://www.figma.com/design/Q9Su8EOrx985SuIz2yw0Hz/design-file-sprint-13?node-id=0-1&m=dev&t=ctzo8idnSj7xz5bL-1

dit is de live link:https://your-tribe-for-life-profile-card-gold.vercel.app/

Kunnen jullie tips geven over hoe ik het kan verbeteren

@Lmikkers
@kaanKalmi
@koenm
@Robin1224

**Comment by Lmikkers** [comment]
Leuk visite kaartje en idee! 
Misschien alleen beetje verwarrend dat wanneer je op de knop "druk voor meer info", je alleen ziet dat de tekst veranderd, misschien valt dit niet heel erg op. Je zou een popup kunnen doen, of een ander kleurtje meegeven? 
En voor de button zou ik ook een `:hover cursor: pointer` meegeven :). Verder goed dat je het idee hebt uitgewerkt in Figma en met tekst erbij! Dit is meer een tip hoor met op de knop klikken, misschien als je het in het echt hebt gemaakt valt het wel op! En met de animatie erbij.

**Comment by KaanKalmi** [comment]
Ik had liever de achtergrond anders gemaakt en misschien wat meer gedoe erin verwerkt met leuke animaties of iets (we hebben teveel geleerd om niet te includen in je profile card dit jaar!)

**Comment by yujing-student** [comment]
bedankt voor de tips ik heb er een 2de ontwerp uitgemaakt die ik verder nog wil uitbreiden met animaties 
zie hier de link naar figma

https://www.figma.com/design/dtWe8NphDJmwGrjyzw3whR/2de-versie-schets-sprint-13?node-id=0-1&m=dev&t=S1h6ufMWVPEk2I2D-1

de gebruiker ziet het profilecard en drukt op de button vervolgens komt het blok meer over mij in beeld 

![image](https://github.com/user-attachments/assets/90e82223-c43b-4a78-8e0b-7f7e099bacb9)

hier is de livelink: https://your-tribe-for-life-profile-card-gold.vercel.app/
