### ISSUE TITLE
lightouse test 

### ISSUE THREAD

**Issue by yujing-student** [yujing-student/your-tribe-for-life-profile-card#11]
op mobiel in lightouse was dit de conclusie

![Image](https://github.com/user-attachments/assets/5718414c-36f7-4f59-bba7-30939a2d4147)

![Image](https://github.com/user-attachments/assets/5bc54b50-1847-48b6-a474-0759a2652e7e)

![Image](https://github.com/user-attachments/assets/7ece1f38-1e4b-47e9-b3a6-b61caa999de5)

op desktop waren de resulaten beter en dit heb ik na het testen verbetert

![Image](https://github.com/user-attachments/assets/cd0d4b5c-cfbd-4899-89f0-8879504e5a0f)

**Comment by yujing-student** [comment]
de mobiele versie

![Image](https://github.com/user-attachments/assets/e1e09940-6f8d-4c33-94e9-db3b7bc4eae5)

de desktop versie 

![Image](https://github.com/user-attachments/assets/a799a778-e9a4-4ba2-a83a-17c331936f41)


de resultaten zijn verbeterd ten opzichte van de 1ste keer

**Comment by Einanas** [comment]
Geweldig dat je Performance en SEO een hogere waarde heeft gekregen! Ga zo door!!
