### ISSUE TITLE
integreren en  profilcecard live zetten op vercel

### ISSUE THREAD

**Issue by yujing-student** [yujing-student/your-tribe-for-life-profile-card#14]
ik heb deze pagina bezocht en gekeken hoe ik mijn proiflecard online kan zetten en dit is gelukt

https://vercel.com/docs/frameworks/sveltekit#use-vercel-features-with-svelte

in de command line doe je 

`npm i @sveltejs/adapter-vercel`

en in de svelte.config file  pas je deze regel aan naar dit 

`import adapter from '@sveltejs/adapter-vercel';`

vervolgens doe je `npm build` in de command line 
en daarna kan je naar vercel gaan inlogen en add project doen en de repository aanklikken waar je een nieuw project van wilt doen en daarna word je website gedopleyd op vercel

zie hier de livelink:https://your-tribe-for-life-profile-card-gold.vercel.app/

**Comment by yujing-student** [comment]
dit heb ik goed toegepast in de svelte.config

https://github.com/yujing-student/your-tribe-for-life-profile-card/blob/main/svelte.config.js

**Comment by Annevd** [comment]
Het ziet ernaar uit dat je begrijpt wat je hebt gedaan en dat het is gelukt. De livelink werkt!
