### ISSUE TITLE
EventListeners

### ISSUE THREAD

**Issue by Robin1224** [yujing-student/your-tribe-for-life-profile-card#18]
In Svelte hoef je geen eventListeners te gebruiken. Reactivity (oftewel een UI dat reageert op events) is iets wat Svelte allemaal voor jou kan regelen. Hierbij hoef je alleen de svelte on:click property te gebruiken om naar een click event te kunnen luisteren.

https://github.com/yujing-student/your-tribe-for-life-profile-card/blob/9bfcbf347ec0c96d2f8e7a7c9acad4d80f4fb815/src/routes/%2Bpage.svelte#L10-L21

Hier kun je er meer over leren:
https://learn.svelte.dev/tutorial/reactive-assignments

**Comment by yujing-student** [comment]
bedankt voor de feedback ik heb naar de tutorial gekeken en toegepast zie hier de link naar mijn code: https://github.com/yujing-student/your-tribe-for-life-profile-card/blob/5a81711efc78e457f3083ae0f76d1c9382c79751/src/lib/button.svelte#L7-L23
