### ISSUE TITLE
bouwen: sveltekit project opstarten met als voorbeeld repo justus 1ste versie bouwen

### ISSUE THREAD

**Issue by yujing-student** [yujing-student/your-tribe-for-life-profile-card#4]
de docs lezen van svelte om het project op te starten:

```
npm create svelte@latest 
cd myapp
npm install
npm run dev
```

vervolgens 2 files toevoegen de fetchjson en page.server.js 
de server.js aanpassen 
https://github.com/ju5tu5/squadpage-sveltekit/blob/main/src/routes/%2Bpage.server.js

dat moet  deze regel worden
`	const url = 'https://fdnd.directus.app/items/person/9'`

vervolgens checken of de data goed word opgehaald en mijn uitwerking overeenkomt met die van justus
https://github.com/ju5tu5/squadpage-sveltekit

**Comment by yujing-student** [comment]
dit heb ik goed afgerond zie hier de routes map 

https://github.com/yujing-student/your-tribe-for-life-profile-card/tree/main/src/routes

**Comment by Annevd** [comment]
Je hebt het voorbeeld goed aangehouden en je begrijpt wat je moet doen. Goed gedaan!
