### ISSUE TITLE
bouwen: fixen dat ik mijn profielkaartje zie en niet die van mijn squad

### ISSUE THREAD

**Issue by yujing-student** [yujing-student/your-tribe-for-life-profile-card#5]
![Image](https://github.com/user-attachments/assets/96338f4b-e765-44ee-a30d-bd37b114422a)

dit zie ik en dat moet dit zijn

![Image](https://github.com/user-attachments/assets/cce3ccc1-76d3-4c9e-9574-762ab112e1cd)

zie voorbeeld:https://github.com/KaanKalmi/your-tribe-for-life-squad-page/blob/button-component-yujing/src/routes/%2Bpage.js

**Comment by wingsvn** [comment]
Je hebt je eigen gegevens opgehaald en hier netjes een comment op geschreven. Goed verwerkt!
